//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HouseStockApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Debt
    {
        public int DebtId { get; set; }
        public int ApartmentId { get; set; }
        public System.DateTime AsOfDate { get; set; }
        public Nullable<decimal> WaterDebt { get; set; }
        public Nullable<decimal> ElectricityDebt { get; set; }
    
        public virtual Apartment Apartment { get; set; }
    }
}
