//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HouseStockApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int PaymentId { get; set; }
        public int ApartmentId { get; set; }
        public System.DateTime Period { get; set; }
        public decimal PaidAmount { get; set; }
        public Nullable<System.DateTime> PaidAt { get; set; }
    
        public virtual Apartment Apartment { get; set; }
    }
}
