//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HouseStockApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public int RequestId { get; set; }
        public int ApartmentId { get; set; }
        public string ApplicantName { get; set; }
        public string ContactPhone { get; set; }
        public string ProblemDescription { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
    
        public virtual Apartment Apartment { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
